- app/financial-product/_components/ProductCard.tsx
- app/financial-product/_components/ProductIcon.tsx
- app/financial-product/_components/RecommendationCard.tsx
- app/financial-product/page.tsx
- components/ui/Button.tsx
https://github.com/fastcampus-final-project/fast-final-client/issues/15
- 금융 상품 홈화면 레이아웃
> 금융 상품 홈화면 레이아웃

- app/asset-management/_components/NetWorth.tsx
- app/asset-management/page.tsx
- app/globals.css
- app/layout.tsx
- tailwind.config.ts
> #20 
> 자산관리 순 자산영역 드래그 작성
> 뷰포트 크기 설정 변경
> 오버플로우 스크롤 추가
> feat: 자산관리 구조 작업

- components/ui/Input.tsx
> #11, #24
> input 컴포넌트에 누락된 fontSize 추가
> feat: input component의 props에 fontSize 누락수정

- app/auth/signup/_components/PwInput.tsx
- app/auth/signup/_components/SignupForm.tsx
- app/auth/signup/_components/SignupNav.tsx
- app/auth/signup/_components/step-form/StepOneForm.tsx
- app/auth/signup/_components/step-form/StepThreeForm.tsx
- app/auth/signup/_components/step-form/StepTwoForm.tsx
> feat: 회원가입 스텝 통합

- app/(home)/_components/BucketListCard.tsx
- app/(home)/_components/ChallengeCard.tsx
- app/(home)/_components/HomeBanner.tsx
- app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
- app/asset-management/_components/MyAssetsGraphSection.tsx
- app/financial-product/page.tsx
> fix: 드래그 할때 이미지 선택 방지

- app/(home)/_components/consume-weather/ConsumeWeatherCard.tsx
- components/header/IsBackHeader.tsx
> 뒤로가기 헤더 아이콘경로 수정, 홈 날씨이미지 경로 수정
> fix: 뒤로가기 헤더 아이콘경로 수정, 홈 날씨이미지 경로 수정

- app/auth/signup/_components/SignupForm.tsx
- app/budget-calendar/page.tsx
- app/edit-widget/_components/DragOverWidget.tsx
- app/edit-widget/_components/IsEditWidgetItem.tsx
- app/edit-widget/hooks/useDrag.ts
- app/edit-widget/page.tsx
- components/Icon.tsx
- tailwind.config.ts
> refactor: 드래그 카드 선택시 크기 변경 애니메이션 추가

- app/financial-product/comparison/_components/ComparisonSection.tsx
- app/financial-product/comparison/_components/FilteringSection.tsx
- app/financial-product/comparison/select-category/page.tsx
- components/BottomSheet.tsx
- components/ui/Button.tsx
https://github.com/fastcampus-final-project/fast-final-client/issues/77
- 바텀시트 컴포넌트 작성
- 공통UI로 사용할 바텀시트 컴포넌트 작성했습니다. 그런데 받아야하는 props가 많아서 코드한 번 읽어보시고 개선할 점 있다면 말씀해주세요 ㅎㅎ
> feat: 바텀시트 컴포넌트 작성

- app/(home)/_components/HomeWidgetSection.tsx
- app/asset-management/_components/CollectAssetSection.tsx
- app/auth/signup/_components/CheckedGender.tsx
- app/auth/signup/step-3/page.tsx
- app/auth/signup/step-4/page.tsx
- components/ui/Button.tsx
- public/icons/system-icon/search-2.svg
> refactor: step-3 검증 작성

- app/auth/signup/_components/step-form/index.ts
- components/ui/TextButton.tsx
> fix: build error

- actions/serverAction.ts
- app/(home)/_components/HomeWidgetSection.tsx
- app/(home)/_components/widget-item/WidgetBudget.tsx
- app/auth/signup/_components/step-form/index.ts
- components/ui/TextButton.tsx
> fix release (#88)

- app/not-found.tsx
- service/api/fetchOptions.ts
> fix: release env (#91)

- app/financial-product/comparison/_components/ComparisonSection.tsx
- app/financial-product/comparison/select-category/page.tsx
- components/ui/Tab.tsx
- hooks/useQueryString.ts
https://github.com/fastcampus-final-project/fast-final-client/issues/114
- useQueryString 커스텀 훅 작성
> refactor: 커스텀 훅으로 리펙토링

- app/api/cards/comparison/result/route.ts
- app/api/cards/comparison/route.ts
- app/financial-product/comparison/_components/BottomButton.tsx
- app/financial-product/comparison/_components/CardsToCompare.tsx
- app/financial-product/comparison/_components/ComparisonSection.tsx
- app/financial-product/comparison/page.tsx
- app/financial-product/comparison/select-category/page.tsx
- app/financial-product/comparison/select-category/result/page.tsx
- app/financial-product/theme-recommendations/page.tsx
- service/api/financial-product/cards.ts
- types/card.ts
- utils/financial-product/staticData.ts
> feat: 금융상품 페이지 로딩처리

- app/auth/login/_components/LoginForm.tsx
- app/auth/signup/(step-1)/page.tsx
- app/auth/signup/_components/CheckedGender.tsx
- app/auth/signup/layout.tsx
- app/auth/signup/step-2/page.tsx
- app/auth/signup/step-3/page.tsx
> fix: signup hydration err

- app/(home)/(default-home)/_components/MyWalletSkeleton.tsx
- app/(home)/(default-home)/_components/MyWallteBottomSheet.tsx
- app/(home)/(default-home)/layout.tsx
- app/(home)/(default-home)/loading.tsx
- app/(home)/edit-widget/_components/DragContainer.tsx
- app/api/bucket/savingbook/route.ts
- app/api/bucket/spendbook/route.ts
- app/api/wallet/route.ts
- app/api/widget/route.ts
- app/create-bucket/_components/RoundedSkeleton.tsx
- app/create-bucket/_components/step/StepOne.tsx
- app/create-bucket/_components/step/StepTwo.tsx
- app/create-bucket/layout.tsx
- app/create-bucket/loading.tsx
- app/create-bucket/result/loading.tsx
- app/globals.css
- app/layout.tsx
- components/BottomSheet.tsx
- components/ui/LoadingBackdrop.tsx
- context/queryProvider.tsx
- package.json
- service/api/create-bucket/index.ts
- service/api/fetchOptions.ts
- service/api/home/index.ts
- utils/graph-config/options.ts
- yarn.lock
> feat: 로딩 페이지 적용

- app/api/cards/spending-habits/route.ts
- app/api/savings/route.ts
- app/financial-product/_components/FinancialProductBanner.tsx
- app/financial-product/_components/SavingCard.tsx
- app/financial-product/ai-recommendations/_components/SpendingHabitsCardSection.tsx
- app/financial-product/comparison/_components/ComparisonSection.tsx
- app/financial-product/comparison/select-category/page.tsx
- app/financial-product/comparison/select-category/result/page.tsx
- types/card.ts
- types/saving.ts
> fix: UT반영 디자인 수정

- middleware.ts
> 버킷랜딩, 생성 페이지 진입시 경로 안바뀌는 문제 수정
> fix: 미들웨어 경로 변경 수정

- app/auth/login/_components/LoginForm.tsx
- app/auth/signup/_components/SignupFormProvider.tsx
- middleware.ts
- service/api/auth/index.ts
- shared/actions/auth.ts
> feat: 로그인 시 클라이언트 측 사용자 정보 동기화

- app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
- app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
- app/budget-calendar/_components/look-together/SharedMembers.tsx
- app/budget-calendar/_components/shared/Calendar.tsx
- app/budget-calendar/utils/generateMergeData.ts
- service/api/calendar/index.ts
- service/api/calendar/share.ts
- shared/types/budgetCalendarType.ts
- shared/utils/formatNumber.ts
> #176 
> 혼자봐요 캘린더 api  연결
공유한 멤버 api 연결
> 함께봐요 캘린더 연결 진행되어야되는데 반응코드랑 엮여있어서
진행을 고민... 함께 봤으면 좋겠습니다
> feat: budget calendar api 혼자봐요, 공유한 멤버

- app/budget-calendar/_components/look-together/LookTogetherContainer.tsx
- app/budget-calendar/_components/look-together/SharedCalendar.tsx
- app/budget-calendar/_components/look-together/SharedMembers.tsx
- app/budget-calendar/_components/shared/ConsumptionWeather.tsx
- app/budget-calendar/_components/shared/RegretSpending.tsx
- service/api/budget/index.ts
- shared/types/budgetCalendarType.ts
- shared/types/response/targetBudget.ts
> #183 
> 공유한 멤버 제목에 이름
멤버의 목표 예산 사용률 조회
> feat: 함께봐요 공유한 멤버 연결

- app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
- components/BottomSheet.tsx
> refactor: bottom sheet isBack 수정

- app/budget-calendar/_components/shared/RegretSpending.tsx
- app/budget-calendar/consumption/page.tsx
- 함께봐요랑 같은 부분이라 맞게 수정
> #188 
> 소비분석 소비날씨, 후회 소비 user 전달 수정
> feat: 소비분석 소비날씨, 후회 소비 user 전달 수정

- app/budget-calendar/consumption/_components/MonthSpending.tsx
- app/budget-calendar/consumption/_components/SpendingCategories.tsx
- app/budget-calendar/consumption/page.tsx
> feat: 소비내역 이름 받아오기

- app/(home)/(default-home)/@widgetSection/page.tsx
> refactor: widgetSection session 없을시 fetch 않게 수정

- app/bucket-landing/_components/part-one/BucketLandingPartOneFourthSection.tsx
#209 
> 버킷랜딩 파트1 섹션4 이미지 크기 변경
> fix: 버킷랜딩 파트1 섹션4 이미지 크기 변경

- app/bucket-landing/_components/part-one/BucketLandingPartOneFifthSection.tsx
- app/bucket-landing/_components/part-one/BucketLandingPartOneFirstSection.tsx
- app/bucket-landing/_components/part-one/BucketLandingPartOneSecondSection.tsx
- app/bucket-landing/_components/part-two/BucketLandingPartTwoSecondSection.tsx
- app/financial-product/comparison/_components/BottomButton.tsx
- app/financial-product/comparison/_components/ComparisonSection.tsx
- app/financial-product/comparison/_components/FilteringSection.tsx
- app/financial-product/comparison/_components/InvalidPopup.tsx
- app/financial-product/comparison/_components/SelectCardCompany.tsx
- app/financial-product/comparison/_components/SelectFiltering.tsx
- app/financial-product/comparison/_components/ValidPopup.tsx
- app/financial-product/comparison/select-category/_components/CategoryCard.tsx
- app/financial-product/comparison/select-category/_components/SelectCategory.tsx
- components/ui/Button.tsx
#210 
> QA 수정사항 적용했습니다 (버킷랜딩, 금융상품)
> QA: bucket landing

- app/budget-calendar/_components/look-alone/ExpensCalendarBox.tsx
- app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
- app/budget-calendar/_components/look-alone/ManagementBottomSheet.tsx
- app/budget-calendar/_components/look-alone/TargetBudgetBottomSheet.tsx
- app/budget-calendar/_components/look-alone/TargetModifyBottomSheet.tsx
- components/header/DefaultHeader.tsx
- service/api/calendar/index.ts
- shared/types/budgetCalendarType.ts
- shared/types/response/targetBudget.ts
> #215 
> 목표 예산 설정 수정 관리
로그아웃시 reactquery 데이터 제거
> feat: 목표 예산 설정 수정 관리

- app/budget-calendar/_components/look-alone/LookAloneContainer.tsx
> fix: iphone 오류 수정
